name: river-mechanics
channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy
  - notebook
  - ipywidgets
  - matplotlib
  - pandas
  - ipyleaflet
  - ipympl
  - pythreejs
  - bqplot
  - voila
  - gdal
  - laspy
  - owslib 